FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o app-bluengo-worker .  

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/app-bluengo-worker ./

EXPOSE 8080

# CMD ["./app-bluengo-worker", "server"]
ENTRYPOINT ["app-bluengo-worker", "server"]