apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distcc
  labels:
    app: distcc
spec:
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      labels:
        app: distcc
    spec:
      containers:
      - name: distcc
        image: bensuperpc/distcc:ubuntu-22.04
        command: ["sleep", "0"]
        ports:
        - containerPort: 3632
          hostPort: 55000