apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distcc
  namespace: default
  labels:
    app: distcc-devtool
spec:
  selector:
    matchLabels:
      name: distcc-devtool
  template:
    metadata:
      labels:
        name: distcc-devtool
    spec:
      containers:
      - name: distcc
        image: bensuperpc/distcc:ubuntu-22.04
        args: ["sleep", "0"]
        ports:
        - containerPort: 3632
          hostPort: 55000
          protocol: TCP
