apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: distcc
  labels:
    app: distcc
spec:
  selector:
    matchLabels:
      app: distcc
  template:
    metadata:
      labels:
        app: distcc
    spec:
      containers:
      - name: distcc
        image: bensuperpc/distcc:debian
        command: ["/usr/bin/distccd", "--daemon", "--no-detach", "--user", "distcc", "--log-level=info", "sleep 0"]
        ports:
        - containerPort: 3632
          hostPort: 55000