name: Build and Push Docker Images to AWS ECR

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: eu-central-1
  AWS_ECR_URL: 248189943700.dkr.ecr.eu-central-1.amazonaws.com/app-bluengo-gi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL

      - name: Build Docker Images
        run: |
          docker build -t $AWS_ECR_URL:app-bluengo-server -f ./Dockerfile_server .
          docker build -t $AWS_ECR_URL:app-bluengo-worker -f ./Dockerfile_worker .

      - name: Push Docker Images to ECR
        run: |
          docker push $AWS_ECR_URL:app-bluengo-server
          docker push $AWS_ECR_URL:app-bluengo-worker